apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: java-app
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: uliseslarraga/internal-lab:demo-k8s
        name: demo
        resources: {}
status: {}
